# Custom properties
title: EA Security Policies
description: >-
  The following addresses core policies used by EA to maintain compliance and assure the proper protections of infrastructure used to store, process, and transmit ePHI for EA Customers.
keywords: Security, Compliance, Software, Infrastructure, Documentation
production_url: "https://effortlessdev.github.io/policies/"
git_url: "https://github.com/EffortlessDev/policies"

# Privacy officer
po_name: "Michael Ross"
po_email: privacy_officer@effortlessadmin.com

# Security officer
so_name: "David Reid"
so_email: security_officer@effortlessadmin.com

# President & CEO
president_name: "David Ross"
president_email: dross@effortlessadmin.com

# CTO
cto_name: "David Reid"
cto_email: dreid@effortlessadmin.com

# Generic emails
compliance_reports_email: compliance-reports@effortlessadmin.com
security_email: privacy@effortlessadmin.com
password_reset_email: password-reset@effortlessadmin.com

# Serving
baseurl: "/policies"
url: "http://localhost:4000/"
redirects: yes

# Conversion
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-email-protect

kramdown:
  auto_ids: false

# SASS
sass:
  sass_dir: assets/_sass

# Collections
collections:
  chapters:
    output: true
    permalink: /chapters/:path/
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      hidden: true
      layout: default

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md