title: EA Security Policies
email: security@effortlessadmin.com
description: >-
  The following addresses core policies used by EA to maintain compliance and assure the proper protections of infrastructure used to store, process, and transmit ePHI for EA Customers.
keywords: Security, Compliance, Software, Infrastructure, Documentation
baseurl: "/"
url: "http://localhost:4000/"
twitter_username: effortlessdev
github_username:  effortlessdev
redirects: yes

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata

# SASS
sass:
  sass_dir: assets/_sass

# Collections
collections:
  chapters:
    output: true
    permalink: /chapters/:path/

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      hidden: true
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md